version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
      - ./vendor:/var/www/vendor
      - ./composer.json:/var/www/composer.json
      - ./storage/logs:/var/log/app
    environment:
      # PHP Configuration from environment variables
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-512M}
      - PHP_UPLOAD_MAX_FILESIZE=${PHP_UPLOAD_MAX_FILESIZE:-128M}
      - PHP_POST_MAX_SIZE=${PHP_POST_MAX_SIZE:-128M}
      - PHP_MAX_EXECUTION_TIME=${PHP_MAX_EXECUTION_TIME:-600}
      - PHP_OPCACHE_ENABLE=${PHP_OPCACHE_ENABLE:-1}
      - PHP_OPCACHE_MEMORY=${PHP_OPCACHE_MEMORY:-256}
      # Application environment
      - APP_ENV=${APP_ENV:-development}
      - APP_DEBUG=${APP_DEBUG:-true}
    env_file:
      - env.docker.example
    restart: unless-stopped
    command: >
      sh -c "/usr/local/bin/configure-php.sh && 
             /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf"

  # Optional: Add MySQL service if needed
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-devframework}
      MYSQL_DATABASE: ${DB_DATABASE:-devframework}
      MYSQL_USER: ${DB_USERNAME:-devframework}
      MYSQL_PASSWORD: ${DB_PASSWORD:-devframework}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    profiles:
      - with-mysql

volumes:
  mysql_data:
